### ISSUE TITLE
build from clone unintuitive and insufficiently documented

### ISSUE THREAD

**Issue by GaryHendrick** [jwgrenning/tddec-code#2]
After cloning the repo, and attempting to enter tddec-code/code to begin build, mutliple errors and warnings are immediately obstructive.  A basic installation of cpputest using `apt-get` will not satisfy the build dependences for `tddec-code/code/MakefileCppUtest.mk`. 

The first issue includes setting to the CPPUTEST_HOME, and results in:
`MakefileCppUTest.mk:60: /build/MakefileWorker.mk: No such file or directory`

However, I may be mistaken, but I don't see a clear indication in the tddec book that this is where CPPUTEST_HOME should be set.  In fact, even the online cpputest documentation is quite unclear on what value CPPUTEST_HOME should have.

Once the user determines that CPPUTEST_HOME should be set, not to an install directory available from the apt package `cpputest`, but only from the cpputest source, then they encounter a new link in the error chain, seen here:

https://github.com/cpputest/cpputest/issues/991

Thank you

**Comment by jwgrenning** [comment]
Hi Gary

A lot has changed in CppUTest since the book.  There was not apt-get 
install, so the book code does not work with apt-get install.

I just updated the instructions in the README.md file.  Let me know if I 
can help.


Hope that helps, James

p.s. You might find my remote delivered live via the web TDD training 
helpful.
https://wingman-sw.com/training/remote-delivered-tdd

p.p.s sorry about the sales message


--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by jwgrenning** [comment]
Hi again Gary

you also might find this helpful 
https://github.com/jwgrenning/cpputest-starter-project

James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by GaryHendrick** [comment]
Thanks James, and thanks for the sample project link. No worries about the sales effort, it's all good.  I'm running through the book, but I'll keep the remote training in mind down the road.

I've got it up and running now too, there were a handful of other issues with -Werror being set, and -Wno-c++14-compat, not being set within recent cpputest builds.  It looks like your starter project takes care of that.

However, I think that the current Makefile will break due to a bug in cpputest:

https://github.com/cpputest/cpputest/issues/115#issuecomment-232757353

This latest bug isn't on you, but hopefully that'll help anyone who ends up running through the samples.
